baseurl = "http://shyr.github.io/"
copyright = "All rights reserved"
disqusshortname = "shyr.github.io"
languagecode = "ko-KR"
paginate = 5
pluralizelisttitles = false
theme = "hugo-theme-docdock"
title = "stephen's blog"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/"
weight = -120
[[menu.main]]
name = "Github repos"
pre = "<h3>Follow me</h3>"
url = "https://github.com/shyr"
weight = 100
[[menu.main]]
name = "Facebook"
url = "https://facebook.com/shyr"
weight = 101

[params]
author = "Stephen Moon"
authorlocation = "Korea"
authorbio = "IT software and Security Engineer, Open source enthusiast."
cover = "images/cover_polenord.jpg"
description = "Knowing is not enough; we must apply. Willing is not enough; we must do."
githubName = "vjeantet"
googleAnalyticsUserID = "UA-91453496-1"
hideHUGOSupport = true
logo = "images/logo.png"
twitterName = "vjeantet"
[permalinks]
post = "/:slug/"
[sitemap]
ChangeFreq = ""
Filename = "sitemap.xml"
Priority = "-1"
